### PR TITLE
Feature/ocpp 21

### PR DESCRIPTION
**Pull request by m-dhooge**
## Proposed changes

Many thanks for your work on OCPP 2.1.
In order to be able to compile and run the 2.1 examples (from another branch…), I had to modify the code.
#d81f4db fixes compilation errors in name mismatches.
#85e1500 fixes a runtime validation error when the Authorization certificate is nil.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by m-dhooge** [comment]
I created this `ast-grep` rule to search for missing `omitempty`. It was only missing once -- but in several branches.
(had to change its extension from .yaml for github to accept it!)

[ast-grep_omitempty-validate.txt](https://github.com/user-attachments/files/27201517/ast-grep_omitempty-validate.txt)

**Review by xBlaz3kx — APPROVED** [review]
